name: build_support
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.4.0


dependencies:
  path:
  dev_build:
  process_run: '>=1.0.0+3'
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
      ref: dart3a

dev_dependencies:
  lints:
  test:
