name: build_support
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.9.0


dependencies:
  path: ">=1.9.0"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
